In [3]:
import pandas as pd
import os

In [14]:
data_to_load = "Resources/spreadspoke_scores.csv"
games_df = pd.read_csv(data_to_load)

In [15]:
games_df.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62.0,NaN

In [20]:
games_df = games_df.dropna(subset=['team_favorite_id', 'spread_favorite', 'over_under_line'], how='all')

In [25]:
games_df.head(10)

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
538,1/12/1969,1968,Superbowl,True,Baltimore Colts,7.0,16.0,New York Jets,IND,-18.0,40,Orange Bowl,True,66.0,12.0,80.0,Rain
727,1/11/1970,1969,Superbowl,True,Kansas City Chiefs,23.0,7.0,Minnesota Vikings,MIN,-12.0,39,Tulane Stadium,True,55.0,14.0,84.0,Rain
2267,1/15/1978,1977,Superbowl,True,Dallas Cowboys,27.0,10.0,Denver Broncos,DAL,-6.0,39,Louisiana Superdome,True,72.0,0.0,NaN,DOME
2500,1/21/1979,1978,Superbowl,True,Dallas Cowboys,31.0,35.0,Pittsburgh Steelers,PIT,-3.5,37,Orange Bowl,True,71.0,18.0,84.0,Rain
2508,9/2/1979,1979,1,False,New Orleans Saints,34.0,40.0,Atlanta Falcons,NO,-5.0,32,Louisiana Superdome,False,72.0,0.0,NaN,DOME
2511,9/2/1979,1979,1,False,Seattle Seahawks,16.0,33.0,San Diego Chargers,SEA,-2.0,42.5,Seattle Kingdome,False,72.0,0.0,NaN,DOME
2519,9/9/1979,1979,2,False,Detroit Lions,24.0,27.0,Washington Redskins,PICK,0.0,35.5,Pontiac Silverdome,False,72.0,0.0,NaN,DOME
2534,9/16/1979,1979,3,False,Houston Oilers,20.0,6.0,Kansas City Chiefs,TEN,-5.0,37,Houston Astrodome,False,72.0,0.0,NaN,DOME
2537,9/16/1979,1979,3,False,New Orleans Saints,14.0,26.0,Philadelphia Eagles,NO,-3.0,42,Louisiana Superdome,False,72.0,0.0,NaN,DOME
2540,9/16/1979,1979,3,False,Seattle Seahawks,27.0,10.0,Oakland Raiders,SEA,-3.0,44,Seattle Kingdome,False,72.0,0.0,NaN,DOME

In [30]:
games_df.to_csv('gamesdata.csv', index=False)